name: Keep Render Service Awake

on:
  schedule:
    # Every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # allow manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://prod-manager-q1ps.onrender.com
